### ISSUE TITLE
How can i get the solution result?

### ISSUE THREAD

**Issue by zfx-code** [muhos/ParaFROST#2]
Hello, I'm trying to use your SAT solver to solve the problem of CNF format, for example:
              parafrost test.cnf
but I can't find any extra options for the output.
    Just like if it is satisfiable, I hope to save a result to solution.out. 
    How should this be done?
    Looking forward to your reply, thank you!

**Comment by muhos** [comment]
No option for that is available as you can easily redirect the output by the command `parafrost test.cnf > solution.out`. If you are interested only in the outcome SAT/UNSAT (without colors), you can use the quiet option `-q`.

**Comment by zfx-code** [comment]
OK, thanks for your reply!

**Comment by zfx-code** [comment]
I just try again and I see what you mean.
This SAT solver only output SAT or UNSAT,  
but can't output the the values of variable(if it is SAT), right?
I've been looking for SAT solvers that efficiently parallel SAT problems, 
because of the size of the problem I'm solving and the low configuration of my computer.
In fact, the speed of your SAT solver is as much fast as minisat
(I can only use CPU because I run it in a cloud server)
and I believe that use GPU will be faster.
Thank you!

**Comment by muhos** [comment]
The model of a SAT formula can be printed with `-model -modelprint`. For more options use `-h`. The performance of the solver can be different from a particular formula to another, so I wouldn't be surprised if minisat was as fast as the CPU version on the formula you tested.

**Comment by zfx-code** [comment]
Dear muhos
I was in touch with you earlier,&nbsp;
and now I want to use Parafrost's GPU version to solve SAT formula problem.
But my cloud servers Linux system don't have GPUs.
I noticed that the paper of Parafrost said it has Windows version.
So could you please give me an GPU executable file under Windows system?
Just like parafrost_gpu.exe ...





I wish you all the best!

Thank you!


张福鑫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "muhos/ParaFROST"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月26日(星期二) 晚上8:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2)





 
Closed #2 as completed.

**Comment by muhos** [comment]
Hello zfx-code, here is the executable file you asked: [parafrost_gpu.exe](https://easyupload.io/1bx6x9). In order to show the colors properly, please run it on a Windows power shell. I plan later to add a C macro to disable the colors if needed.

Let me know if it runs ok.

Best regards,
Muhammad

**Comment by zfx-code** [comment]
Dear muhuo
Thank you very much!
But when I click this link: https://easyupload.io/1bx6x9 
It told me "file not found".(I have login it)
So maybe there are some problems?









张福鑫
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "muhos/ParaFROST"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2)





 
Hello zfx-code, here is the executable file you asked: parafrost_gpu.exe. In order to show the colors properly, please run it on a Windows power shell. I plan later to add a C macro to disable the colors if needed.
 
Let me know if it runs ok.
 
Best regards,
 Muhammad

**Comment by muhos** [comment]
Hello zfx-code, here is the executable file you asked: [parafrost_gpu.exe](https://file.io/9KkCTgYcr8KM). In order to show the colors properly, please run it on a Windows power shell. I plan later to add a C macro to disable the colors if needed.

Let me know if it runs ok.

Best regards,
Muhammad

**Comment by muhos** [comment]
Sorry for the broken link, I updated it!

**Comment by muhos** [comment]
> Dear muhuo Thank you very much! But when I click this link: https://easyupload.io/1bx6x9 It told me "file not found".(I have login it) So maybe there are some problems? 张福鑫 ***@***.*** &nbsp;
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "muhos/ParaFROST" ***@***.***&gt;; 发送时间:&nbsp;2022年7月27日(星期三) 下午3:59 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2) Hello zfx-code, here is the executable file you asked: parafrost_gpu.exe. In order to show the colors properly, please run it on a Windows power shell. I plan later to add a C macro to disable the colors if needed. Let me know if it runs ok. Best regards, Muhammad — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Sorry for the broken link, I updated it to [parafrost_gpu.exe](https://file.io/9KkCTgYcr8KM)

**Comment by zfx-code** [comment]
Hello Muhammad
I'm sorry to bother you so often, 
but there still seem to be some problems with file sharing this time.





张福鑫
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "muhos/ParaFROST"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 下午4:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2)





 
Sorry for the broken link, I updated it!

**Comment by muhos** [comment]
It seems the host is keeping deleting my file after a while! It suspects it's a malware I think.

**Comment by muhos** [comment]
Could you try again with the above link, I used google drive this time.

**Comment by zfx-code** [comment]
I try again, it still told me "The transfer you requested has been deleted."
Maybe you can upload it in Github.
Thank you.


张福鑫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "muhos/ParaFROST"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2)





 
Could you try again with the above link, I used google drive this time.

**Comment by muhos** [comment]
> I try again, it still told me "The transfer you requested has been deleted." Maybe you can upload it in Github. Thank you. 张福鑫 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "muhos/ParaFROST" ***@***.***&gt;; 发送时间:&nbsp;2022年7月27日(星期三) 下午4:35 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2) Could you try again with the above link, I used google drive this time. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Transfer blocked means a security software on your side blocked the download. Because I tested it on my side and the file is successfully downloaded.

**Comment by zfx-code** [comment]
I close my security software, and still can't download.
I see that, maybe because you downloaded it, and it has been deleted.
Thank you.&nbsp;







张福鑫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "muhos/ParaFROST"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2)





  
I try again, it still told me "The transfer you requested has been deleted." Maybe you can upload it in Github. Thank you. 张福鑫 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "muhos/ParaFROST" @.&gt;; 发送时间:&nbsp;2022年7月27日(星期三) 下午4:35 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2) Could you try again with the above link, I used google drive this time. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Transfer blocked means a security software on your side blocked the download. Because I tested it on my side and the file is successfully downloaded.

**Comment by muhos** [comment]
> I close my security software, and still can't download. I see that, maybe because you downloaded it, and it has been deleted. Thank you.&nbsp; 张福鑫 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "muhos/ParaFROST" ***@***.***&gt;; 发送时间:&nbsp;2022年7月27日(星期三) 下午4:44 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2) I try again, it still told me "The transfer you requested has been deleted." Maybe you can upload it in Github. Thank you. 张福鑫 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "muhos/ParaFROST" @.&gt;; 发送时间:&nbsp;2022年7月27日(星期三) 下午4:35 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2) Could you try again with the above link, I used google drive this time. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; Transfer blocked means a security software on your side blocked the download. Because I tested it on my side and the file is successfully downloaded. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

No, because I have it on my Google drive. It cannot delete files by its own. Check if your browser or Windows security or any kind firewall blocked the download. First of all double check you are using the correct link: 
[](https://drive.google.com/file/d/1rjFYH5eqmZ5F-ulQ-S-29M7Cifct40-O/view?usp=sharing)

**Comment by muhos** [comment]
Somehow I missed this feature on Github ;) I uploaded it here as well. [parafrost_gpu.zip](https://github.com/muhos/ParaFROST/files/9196943/parafrost_gpu.zip)

**Comment by zfx-code** [comment]
Hello Muhammad,
I look some introduction
My GPU is intel, not&nbsp;NVIDIA.
So it can't run cuda or use GPU to solve SAT problem.
But I'm still grateful for your help.


I wish you all the best!




张福鑫
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "muhos/ParaFROST"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2)





 
Somehow I missed this feature on Github ;) I uploaded it here as well. parafrost_gpu.zip

**Comment by muhos** [comment]
> Hello Muhammad, I look some introduction My GPU is intel, not&nbsp;NVIDIA. So it can't run cuda or use GPU to solve SAT problem. But I'm still grateful for your help. I wish you all the best! 张福鑫 ***@***.*** &nbsp;
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "muhos/ParaFROST" ***@***.***&gt;; 发送时间:&nbsp;2022年7月27日(星期三) 下午5:27 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [muhos/ParaFROST] How can i get the solution result? (Issue #2) Somehow I missed this feature on Github ;) I uploaded it here as well. parafrost_gpu.zip — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

No problem, I'm glad to help.
