### ISSUE TITLE
GPU version error

### ISSUE THREAD

**Issue by zfx-code** [muhos/ParaFROST#3]
Hello, I run the GPU version in Linux system.
And it told me that error: "cannot map to cores for SM 8.6. Default to use 64 Cores/SM".
So what's the meaning of this?

Thank you!
![GPU报错信息](https://user-images.githubusercontent.com/65902313/182021032-831e52a0-3757-4021-90b5-2a82ac6fb9c2.png)

**Comment by muhos** [comment]
Could you send me a scrrenshot of the output after using this option (--verbose=2), this will give me more steps to figure out what's going on here. Also, please send me the CNF formula you used, so I can hopefully reproduce the error!

**Comment by zfx-code** [comment]
Thank you.
I change a Linux cloud server and now it can run without error.
And I want to ask a question about the complexity of SAT problem.
Such as a 10000 literals and 50000 clauses, my guess is the high probability is UNSAT.
I'm not sure if it's still running, because it's been running for a long time.(not stop)
The worst case scenario is exhaustive 2^10000 values?
About how long does it take to give an UNSAT solution?

Attached is one of the CNF formulas I want to solve.




张福鑫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "muhos/ParaFROST"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月3日(星期三) 凌晨2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [muhos/ParaFROST] GPU version error (Issue #3)





 
Could you send me a scrrenshot of the output after using this option (--verbose=2), this will give me more steps to figure out what's going on here. Also, please send me the CNF formula you used, so I can hopefully reproduce the error!

**Comment by muhos** [comment]
Yes, 2^10000 is the worst scenario by far but that could happen only in DPLL solvers. In CDCL solvers like ParaFROST proving UNSAT is much faster due to learning and inprocessing; still, the solving time relies on the hardness of the CNF formula. A standard time limit could be set to 5000 seconds like in SAT competitions.

You can save the the solver progress to a file and check that file from time to time. Usually when the number of variables and clauses remained (after inprocessing) are getting less and less over time, that's a good indication of the effectiveness of the inprocessing techniques and it's likely to be solved soon (could be days though). 

PS. I think you forgot to attach the CNF.

**Comment by zfx-code** [comment]
Thank you! I understand it.
By the way, in last email I send the CNF formula as attach.
And I send it to you again.


Wish you all the best!







张福鑫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "muhos/ParaFROST"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月3日(星期三) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [muhos/ParaFROST] GPU version error (Issue #3)





 
Yes, 2^10000 is the worst scenario by far but that could happen only in DPLL solvers. In CDCL solvers like ParaFROST proving UNSAT is much faster due to learning and inprocessing; still, the solving time relies on the hardness of the CNF formula. A standard time limit could be set to 5000 seconds like in SAT competitions.
 
You can save the the solver progress to a file and check that file from time to time. Usually when the number of variables and clauses remained (after inprocessing) are getting less and less over time, that's a good indication of the effectiveness of the inprocessing techniques and it's likely to be solved soon (could be days though).
 
PS. I think you forgot to attach the CNF.

**Comment by zfx-code** [comment]
Thank you! I understand it.
By the way, in last email I send the CNF formula as attach.
And I send it to you again(in github).

Wish you all the best!

[primate_inv_mc=7.zip](https://github.com/muhos/ParaFROST/files/9249497/primate_inv_mc.7.zip)

**Comment by zfx-code** [comment]
Oh, by the way, I want to the executable file in Windows(CPU version).
Thank you!

**Comment by muhos** [comment]
> 

[parafrost_cpu.zip](https://github.com/muhos/ParaFROST/files/9252400/parafrost_cpu.zip)

**Comment by muhos** [comment]
> Thank you! I understand it. By the way, in last email I send the CNF formula as attach. And I send it to you again(in github).
> 
> Wish you all the best!
> 
> [primate_inv_mc=7.zip](https://github.com/muhos/ParaFROST/files/9249497/primate_inv_mc.7.zip)

Thanks!

**Comment by muhos** [comment]
> Hello, I run the GPU version in Linux system. And it told me that error: "cannot map to cores for SM 8.6. Default to use 64 Cores/SM". So what's the meaning of this?
> 
> Thank you! ![GPU报错信息](https://user-images.githubusercontent.com/65902313/182021032-831e52a0-3757-4021-90b5-2a82ac6fb9c2.png)

I realesed a new version (3.2.1) and ran the given CNF on a NVIDIA A100-SXM4-40GB (compute cap: 8.0, same architecture as the RTX 3070) without any problems. So, I guess the bug was fixed.

**Comment by zfx-code** [comment]
Thank you!
I found the reason of the error is I forgot to install cuda(it's my problem).&nbsp;
And now I can run GPU version in Linux systems, the Parafrost helped me solve about 7/8 problems.(the speed of giving UNSAT is really fast, now the longest UNSAT is ten days).
I guess I have three most difficult problems maybe need two to three months.(large probability is UNSAT, I hope it can as soon as possible run a result.)


Best wishes to you!



---Original---
From: "Muhammad ***@***.***&gt;
Date: Sat, Aug 13, 2022 17:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [muhos/ParaFROST] GPU version error (Issue #3)




  
Hello, I run the GPU version in Linux system. And it told me that error: "cannot map to cores for SM 8.6. Default to use 64 Cores/SM". So what's the meaning of this?
 
Thank you! 
  
I realesed a new version (3.2.1) and ran the given CNF on a NVIDIA A100-SXM4-40GB (compute cap: 8.0, same architecture as the RTX 3070) without any problems. So, I guess the bug was fixed.

**Comment by muhos** [comment]
> Thank you! I found the reason of the error is I forgot to install cuda(it's my problem).&nbsp; And now I can run GPU version in Linux systems, the Parafrost helped me solve about 7/8 problems.(the speed of giving UNSAT is really fast, now the longest UNSAT is ten days). I guess I have three most difficult problems maybe need two to three months.(large probability is UNSAT, I hope it can as soon as possible run a result.) Best wishes to you!
> […](#)
> ---Original--- From: "Muhammad ***@***.***&gt; Date: Sat, Aug 13, 2022 17:32 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [muhos/ParaFROST] GPU version error (Issue #3) Hello, I run the GPU version in Linux system. And it told me that error: "cannot map to cores for SM 8.6. Default to use 64 Cores/SM". So what's the meaning of this? Thank you! I realesed a new version (3.2.1) and ran the given CNF on a NVIDIA A100-SXM4-40GB (compute cap: 8.0, same architecture as the RTX 3070) without any problems. So, I guess the bug was fixed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Great and best of luck solving the remaining problems.
