### ISSUE TITLE
STDIN option for file

### ISSUE THREAD

**Issue by DoINeedATag** [muhos/ParaFROST#4]
Hello! I am rather out of my depth here with SAT solvers and such. However I have been playing with this project: https://github.com/R-O-C-K-E-T/Factorio-SAT

They give an option to use other solvers instead of their standard one via `--solver="cmd:/path/to/solver` however all the other solvers I have used accept input via STDIN, kissat, cadical, gimsatul, GpuShareSat, etc. Would it be possible to add STDIN as an input option? I have tried unsuccessfully to find a work around.

I would love to try ParaFROST out on this project.

Thank you!

**Comment by muhos** [comment]
Hello, thanks for the feedback. That's one of the features I also wanted to have in ParaFROST. Sure, I will try to add it in the next few days.

**Comment by muhos** [comment]
The stdin handling is now available in the latest release.

**Comment by DoINeedATag** [comment]
Worked like a charm thank you!
