### ISSUE TITLE
ParaFROST on Windows Subsystem for Linux (WSL2)

### ISSUE THREAD

**Issue by ajohnson1** [muhos/ParaFROST#5]
I have succeeding in getting ParaFROST to compile and run under WSL2 but had to make some minor changes.

This was with a laptop with NVIDIA T1200 laptop GPU, Intel Core i7-11850H processor, Windows 11, WSL2 running Ubuntu 22.04

1. Review https://docs.nvidia.com/cuda/wsl-user-guide/index.html#getting-started-with-cuda-on-wsl
2. Install latest Windows NVIDIA driver from https://www.nvidia.co.uk/download/driverResults.aspx/198565/en-uk (in my case was 528.24).
3. I installed the NVIDIA CUDA toolkit for Windows from https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64 This might not strictly be necessary, but let me check that CUDA worked from Windows with `nvidia-smi`.
4. I followed option 1 to install CUDA into WSL2. https://docs.nvidia.com/cuda/wsl-user-guide/index.html#step-3-set-up-a-linux-development-environment then did a `wsl -shutdown` and restarted my wsl session. `nvidia-smi` should then work from WSL2.
5. Download ParaFrost
6. To avoid compile errors I added ` --std c++14"` to `NVCCFLAGS` to `install.sh` such as the following:
    `/usr/include/c++/11/type_traits:79:52: error: redefinition of ‘constexpr const _Tp std::integral_constant<_Tp, __v>::valu
    ’
       79 |   template<typename _Tp, _Tp __v> 
          |                                                    ^
    /usr/include/c++/11/type_traits:67:29: note: ‘constexpr const _Tp value’ previously declared here    
       67 |       static constexpr _Tp                  value = __v;
           |                             ^~~~~
    nvcc_internal_extended_lambda_implementation:230:8: error: redefinition of ‘struct __nv_hdl_helper_trait_outer<IsMutable,      HasFuncPtrConv, CaptureArgs>::__nv_hdl_helper_trait<Tag, R (C::*)(OpFuncArgs ...) const>’`
7. Changed `NVIDIASMI` in `install.sh` to point to the actual location of `nvidia-smi` in WSL2
8. To avoid a fatal error 'ERROR - CUDA runtime failure due to invalid device ordinal' on `cudaMemAdvise` I followed the advice at https://stackoverflow.com/questions/67115068/unexpected-read-access-violation-error-in-cuda-when-working-with-unified-memory and checked `cudaDeviceGetAttribute(&cmm, cudaDevAttrConcurrentManagedAccess, device_to_check);`

Perhaps some of these steps could be merged back into the code.

Thank you for providing ParaFROST - it is an interesting project, though hasn't yet been faster on a couple of my CNF files.

**Comment by muhos** [comment]
Thanks for the suggested solution. 

There was a bug in the install script that prevented the nvcc compiler from reading the default c++ standard which was set to 14. Now, it's fixed along with some other minor issues.

I tried to reproduce step 8 on WSL - Ubuntu 22.04 but could not find any issues with cudaMemAdvice. I double checked with `--verbose=2` and found that cudaMemAdvice was being successfully called by the memory allocator as intended.

**Comment by ajohnson1** [comment]
I still got the cudaMemAdvise problem with the latest code when I built with `./install.sh -g -w -t -l -s`

**Comment by muhos** [comment]
I found out why I couldn't reproduce the problem. In asserting mode enabled by `t`, all assertions were enabled on both host-only and managed-memory variables. The latter caused the memory advice failure which makes sense as the Windows GPU driver is still being used in WSL.

**Comment by ajohnson1** [comment]
Commit https://github.com/muhos/ParaFROST/commit/2cd5e60e8bad808196568e9e00bade9c4f068499 fixes the cudaMemAdvise problem for me.
Other recent commits e.g. https://github.com/muhos/ParaFROST/commit/6ac3bbbbe652eeef00a915f6a1c2321d3f2e23ca fixed the other problems I noted.
Thanks for your prompt attention to this.
