### ISSUE TITLE
How to get the number of solutions?

### ISSUE THREAD

**Issue by liyu0x** [muhos/ParaFROST#6]
Hi, I am using ParaFORST to solve cryptography problems, and how I get the detail of an solution and get the total number of solutions?

Thank you.

**Comment by liyu0x** [comment]
Hi, I get the variables for an solution, but now I want to get total number of all solutions, what should I do?

**Comment by muhos** [comment]
Hello, sorry for my late response. I have been away from developping this project for a while. To get the total number of solutions, you have to do model counting. A naive algorithm is to call a SAT solver iteratively considering previous models. More info. can be found here: https://www.cs.cornell.edu/~sabhar/chapters/ModelCounting-SAT-Handbook-prelim.pdf

**Comment by liyu0x** [comment]
> Hello, sorry for my late response. I have been away from developping this project for a while. To get the total number of solutions, you have to do model counting. A naive algorithm is to call a SAT solver iteratively considering previous models. More info. can be found here: https://www.cs.cornell.edu/~sabhar/chapters/ModelCounting-SAT-Handbook-prelim.pdf

Never mind, and thank you for responsing me, I will read it.
